### ISSUE TITLE
DTB-BLACKBERRY.dts out of date with HW. Keyboard does not function due to remapped I2C IO assignments.

### ISSUE THREAD

**Issue by tannerpa** [Groboards/giantboard-tools#13]
The revised hardware for the 'blackberry' featherwing has changed the touchpad I2C controller from STMPE811 to TSC2004IR  which moved the keyboard interrupt from GPIO2 on STMPE811 directly to GPIO6 on the featherwing. This maps to PB5 on the Giantboard.

OLD:
https://www.solder.party/docs/keyboard-featherwing/rev1/schematics_keyboard_featherwing.png

NEW:
https://www.solder.party/docs/keyboard-featherwing/rev2/schematics_keyboard_featherwing.png

**Comment by aryn-0xide** [comment]
Any chance you got this working?  I just encountered this after flashing the blackberry img file.  Debian loads up but I keyboard isn't being registered so just sits there with blinking cursor.  I'm not very familiar with the process for updating/recompiling a .img file to reflash to the SD card.  In theory, it should be easy enough to edit the DTB-BLACKBERRY.dts with correct pin maping/device info and then recompile it to .dtbo but I haven't quite figured out how to do it.

**Comment by Groguard** [comment]
You'll need to likely solder a jumper wire from the interrupt on the Giant Board to the interrupt on the keyboard featherwing from GPIO6 on the keyboard to PD31 on the Giant Board Thats how I made it work before. The Giant Board will never be truley compatible because the Giant Board only has 2 interrupts, none of which are in the correct positions. The interrupts cant be remapped either.
